# frozen_string_literal: true

# Run inside the Discourse container directly or through discourse_configure_sso.sh:
# RAILS_ENV=production bundle exec rails runner /tmp/apply_zh_overrides.rb

translations = {
  "admin_js.admin.reports.back_to_dashboard" => "返回信息中心",
  "admin_js.admin.upcoming_changes.depends_on_notice" => "此更改需要先启用 %{dependencyLinks}。",
  "admin_js.admin.upcoming_changes.enabled_for_options.specific_groups_with_group_names.one" => "群组 %{groupNames}",
  "admin_js.admin.config.logo.form.og_image_source.title" => "OpenGraph 图片来源",
  "admin_js.admin.config.logo.form.og_image_source.description" => "选择如何为没有图片的话题提供 OpenGraph 预览图。",
  "admin_js.admin.config.logo.form.og_image_source.uploaded" => "使用已上传的图片",
  "admin_js.admin.config.logo.form.og_image_source.generated" => "为每个话题生成图片",
  "admin_js.admin.config.logo.form.generate_topic_og_image.title" => "生成话题 OpenGraph 图片",
  "admin_js.admin.config.logo.form.generate_topic_og_image.description" => "自动为没有图片的话题生成 OpenGraph 预览图，内容取自话题标题、类别和站点颜色。",
  "admin_js.admin.config.logo.form.og_image_preview.title" => "生成的 OpenGraph 图片预览",
  "admin_js.admin.config.logo.form.og_image_preview.description" => "预览为无图片话题自动生成的 OpenGraph 图片。请输入话题 ID 进行测试。",
  "admin_js.admin.config.logo.form.og_image_preview.topic_id_placeholder" => "例如 123",
  "admin_js.admin.config.logo.form.og_image_preview.placeholder" => "输入话题 ID，然后点击“生成”进行预览。",
  "admin_js.admin.config.logo.form.og_image_preview.error" => "无法生成预览。请检查话题 ID 后重试。",
  "admin_js.admin.config.fonts.backfill_modal.description.one" => "您已更新默认文本大小。是否将此更改应用到 %{count} 位现有用户？",
  "admin_js.admin.config.gifs.title" => "动图",
  "admin_js.admin.config.gifs.header_description" => "配置动图选择器，让用户能够在帖子和聊天消息中搜索并插入动图。弹窗文案可在“自定义/站点文本”中修改。",
  "admin_js.admin.search.result_count.one" => "“%{filter}”有 %{count} 个结果",
  "admin_js.admin.dashboard.up_to_date_newer_commits.one" => "您正在使用最新版本，但还有 %{count} 项新更改可用。",
  "admin_js.admin.dashboard.up_to_date_newer_commits.other" => "您正在使用最新版本，但还有 %{count} 项新更改可用。",
  "admin_js.admin.dashboard.latest_version" => "可用版本",
  "admin_js.admin.dashboard.commit_on_github" => "在 GitHub 上查看提交 %{sha}",
  "admin_js.admin.dashboard.changelog" => "更新日志",
  "admin_js.admin.dashboard.commits_ahead.one" => "自此版本系列开始以来，当前运行版本额外包含 %{count} 项更改",
  "admin_js.admin.dashboard.commits_ahead.other" => "自此版本系列开始以来，当前运行版本额外包含 %{count} 项更改",
  "admin_js.admin.dashboard.site_advice.title.one" => "根据您的站点配置，有 %{count} 个问题需要处理",
  "admin_js.admin.dashboard.site_advice.title.other" => "根据您的站点配置，有 %{count} 个问题需要处理",
  "admin_js.admin.dashboard.backup_count.one" => "%{location} 上有 %{count} 个备份",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.trend.climbing.one" => "+%{count} 人升级",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.trend.dropping.one" => "-%{count} 人降级",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.signups.one" => "+ %{formattedCount} 位注册用户",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.signups.other" => "+ %{formattedCount} 位注册用户",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.signups_title" => "到达此信任级别的新注册用户数",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.count_title" => "此信任级别的成员总数",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.arrivals_aria.one" => "%{count} 位成员升级到此信任级别",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.arrivals_aria.other" => "%{count} 位成员升级到此信任级别",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.demotions_in_aria.one" => "%{count} 位成员降级到此信任级别",
  "admin_js.admin.dashboard.sections.engagement.trust_level_pipeline.demotions_in_aria.other" => "%{count} 位成员降级到此信任级别",
  "admin_js.admin.dashboard.sections.engagement.headline.engaged_but_shrinking.summary" => "用户黏性保持稳定，但每日参与度或新注册数有所下降。",
  "admin_js.admin.dashboard.sections.engagement.headline.growing_but_distracted.title" => "新成员持续注册，但留存情况不佳。",
  "admin_js.admin.dashboard.sections.engagement.headline.growing_but_distracted.summary" => "本周期注册数上升，但用户黏性有所下降。",
  "admin_js.admin.dashboard.sections.engagement.headline.mixed.title" => "本周期的参与度趋势不一致。",
  "admin_js.admin.dashboard.sections.engagement.headline.mixed.summary" => "部分指标上升、部分指标下降，请打开下方卡片查看详情。",
  "admin_js.admin.dashboard.sections.engagement.headline.no_signal.title" => "目前活动量不足，无法总结参与度。",
  "admin_js.admin.dashboard.sections.engagement.headline.no_signal.summary" => "请选择更长的日期范围，或等社区产生更多活动后再查看。",
  "admin_js.admin.dashboard.sections.search.fetch_error" => "无法加载搜索数据，请刷新页面重试。",
  "admin_js.admin.dashboard.sections.search.logging_disabled" => "搜索日志记录已关闭，因此尚未收集搜索数据。请启用<a href=\"%{basePath}/admin/site_settings/category/all_results?filter=log%20search%20queries\">记录搜索查询</a>以开始收集。",
  "admin_js.admin.dashboard.sections.search.logging_disabled_moderator" => "搜索日志记录已关闭，因此尚未收集搜索数据。请联系管理员启用搜索查询记录。",
  "admin_js.admin.dashboard.sections.search.count_headline.last_7_days.one" => "成员在过去 7 天进行了 %{formatted_count} 次站内搜索",
  "admin_js.admin.dashboard.sections.search.count_headline.last_7_days.other" => "成员在过去 7 天进行了 %{formatted_count} 次站内搜索",
  "admin_js.admin.dashboard.sections.search.count_headline.last_30_days.one" => "成员在过去 30 天进行了 %{formatted_count} 次站内搜索",
  "admin_js.admin.dashboard.sections.search.count_headline.last_30_days.other" => "成员在过去 30 天进行了 %{formatted_count} 次站内搜索",
  "admin_js.admin.dashboard.sections.search.count_headline.last_3_months.one" => "成员在过去 3 个月进行了 %{formatted_count} 次站内搜索",
  "admin_js.admin.dashboard.sections.search.count_headline.last_3_months.other" => "成员在过去 3 个月进行了 %{formatted_count} 次站内搜索",
  "admin_js.admin.dashboard.sections.search.count_headline.selected_period.one" => "成员在所选时段进行了 %{formatted_count} 次站内搜索",
  "admin_js.admin.dashboard.sections.search.count_headline.selected_period.other" => "成员在所选时段进行了 %{formatted_count} 次站内搜索",
  "admin_js.admin.dashboard.sections.search.headline.no_signal_title" => "目前搜索活动不足，无法生成总结。",
  "admin_js.admin.dashboard.sections.search.headline.no_signal" => "请选择更长的日期范围，或等成员进行更多搜索后再查看。",
  "admin_js.admin.dashboard.sections.search.headline.content_gaps" => "本周期超过 10% 的成员搜索未产生点击。请查看下方内容缺口，了解缺少哪些内容。",
  "admin_js.admin.dashboard.sections.search.headline.rate_climbing" => "无结果率较上一周期上升，请留意下方的内容缺口。",
  "admin_js.admin.dashboard.sections.search.headline.shrinking" => "搜索量较上一周期下降，但大多数搜索仍能找到内容。",
  "admin_js.admin.dashboard.sections.search.headline.healthy" => "成员持续找到所需内容，搜索量保持稳定或正在增长。",
  "admin_js.admin.dashboard.sections.search.kpi.total_searches.label" => "搜索总数",
  "admin_js.admin.dashboard.sections.search.kpi.total_searches.tooltip" => "社区成员执行的搜索次数。",
  "admin_js.admin.dashboard.sections.search.kpi.no_result_rate.label" => "无结果率",
  "admin_js.admin.dashboard.sections.search.kpi.no_result_rate.tooltip" => "成员未点击任何结果的搜索占比（点击率为 0%）。这可能表示成员正在搜索社区尚未提供的内容。",
  "admin_js.admin.dashboard.sections.search.table.term" => "搜索词",
  "admin_js.admin.dashboard.sections.search.trending.title" => "热门搜索",
  "admin_js.admin.dashboard.sections.search.trending.tooltip" => "成员最常使用的搜索词。",
  "admin_js.admin.dashboard.sections.search.trending.empty" => "本周期没有搜索记录。",
  "admin_js.admin.dashboard.sections.search.content_gaps.title" => "内容缺口",
  "admin_js.admin.dashboard.sections.search.content_gaps.empty" => "本周期没有内容缺口。",
  "admin_js.admin.dashboard.sections.search.content_gaps.badge.no_match" => "无匹配结果",
  "admin_js.admin.dashboard.sections.search.content_gaps.badge.no_match_tooltip" => "点击率为 0% 的搜索词。",
  "admin_js.admin.dashboard.sections.search.content_gaps.badge.poor_match" => "匹配度较低",
  "admin_js.admin.dashboard.sections.search.content_gaps.badge.poor_match_tooltip" => "点击率在 1% 到 20% 之间的搜索词。",
  "admin_js.admin.dashboard.reports_section.description" => "固定标准报告或数据资源管理器查询，以跟踪社区的重要指标。",
  "admin_js.admin.dashboard.reports_section.add" => "添加报告",
  "admin_js.admin.dashboard.reports_section.remove" => "移除报告",
  "admin_js.admin.dashboard.reports_section.no_data" => "没有可显示的数据",
  "admin_js.admin.dashboard.reports_section.modal.title" => "管理报告",
  "admin_js.admin.dashboard.reports_section.modal.search_placeholder" => "搜索报告",
  "admin_js.admin.dashboard.reports_section.modal.counter" => "已添加 %{count} / %{max} 个报告",
  "admin_js.admin.dashboard.reports_section.modal.enable" => "启用 %{title}",
  "admin_js.admin.dashboard.reports_section.modal.disable" => "禁用 %{title}",
  "admin_js.admin.dashboard.reports_section.modal.move_up" => "上移 %{title}",
  "admin_js.admin.dashboard.reports_section.modal.move_down" => "下移 %{title}",
  "admin_js.admin.dashboard.reports_section.modal.footer_note" => "这些更改将应用于所有用户。",
  "admin_js.admin.dashboard.configure.tooltip" => "配置此信息中心面向站点所有用户的显示方式。",
  "admin_js.admin.dashboard.configure.menu_title" => "配置信息中心",
  "admin_js.admin.dashboard.configure.reorder_up" => "上移 %{label}",
  "admin_js.admin.dashboard.configure.reorder_down" => "下移 %{label}",
  "admin_js.admin.dashboard.configure.drag_handle" => "拖动以重新排列 %{label}",
  "admin_js.admin.dashboard.configure.toggle_visibility" => "在信息中心显示 %{label}",
  "admin_js.admin.dashboard.configure.empty_state_admin" => "没有可显示的部分。请打开“配置”启用至少一个部分。",
  "admin_js.admin.dashboard.configure.empty_state_moderator" => "尚未启用任何部分，请联系管理员启用。",
  "admin_js.admin.dashboard.highlights.fetch_error" => "无法加载重点数据，请刷新页面重试。",
  "admin_js.admin.dashboard.highlights.kpi.new_signups.label" => "新注册用户",
  "admin_js.admin.dashboard.highlights.kpi.dau_mau.label" => "日活/月活黏性",
  "admin_js.admin.dashboard.highlights.kpi.new_contributors.label" => "新贡献者",
  "admin_js.admin.dashboard.highlights.kpi.daily_engaged_users.label" => "每日参与用户",
  "admin_js.admin.dashboard.highlights.comparison.last_7_days" => "与过去 7 天相比",
  "admin_js.admin.dashboard.highlights.comparison.last_30_days" => "与过去 30 天相比",
  "admin_js.admin.dashboard.highlights.comparison.last_3_months" => "与过去 3 个月相比",
  "admin_js.admin.dashboard.highlights.comparison.previous_period" => "与上一周期相比",
  "admin_js.admin.dashboard.site_traffic.fetch_error" => "无法加载站点流量，请刷新页面重试。",
  "admin_js.admin.dashboard.site_traffic.headline.last_7_days.one" => "过去 7 天有 %{formatted_count} 次页面浏览",
  "admin_js.admin.dashboard.site_traffic.headline.last_7_days.other" => "过去 7 天有 %{formatted_count} 次页面浏览",
  "admin_js.admin.dashboard.site_traffic.headline.last_30_days.one" => "过去 30 天有 %{formatted_count} 次页面浏览",
  "admin_js.admin.dashboard.site_traffic.headline.last_30_days.other" => "过去 30 天有 %{formatted_count} 次页面浏览",
  "admin_js.admin.dashboard.site_traffic.headline.last_3_months.one" => "过去 3 个月有 %{formatted_count} 次页面浏览",
  "admin_js.admin.dashboard.site_traffic.headline.last_3_months.other" => "过去 3 个月有 %{formatted_count} 次页面浏览",
  "admin_js.admin.dashboard.site_traffic.headline.selected_period.one" => "所选时段有 %{formatted_count} 次页面浏览",
  "admin_js.admin.dashboard.site_traffic.headline.selected_period.other" => "所选时段有 %{formatted_count} 次页面浏览",
  "admin_js.admin.dashboard.site_traffic.trend.up" => "上升 %{percent}",
  "admin_js.admin.dashboard.site_traffic.trend.down" => "下降 %{percent}",
  "admin_js.admin.dashboard.site_traffic.comparison_tooltip.previous_7_days" => "与此前 7 天相比（%{start} 至 %{end}）",
  "admin_js.admin.dashboard.site_traffic.comparison_tooltip.previous_30_days" => "与此前 30 天相比（%{start} 至 %{end}）",
  "admin_js.admin.dashboard.site_traffic.comparison_tooltip.previous_3_months" => "与此前 3 个月相比（%{start} 至 %{end}）",
  "admin_js.admin.dashboard.site_traffic.comparison_tooltip.previous_days.one" => "与前一天相比（%{start} 至 %{end}）",
  "admin_js.admin.dashboard.site_traffic.comparison_tooltip.previous_days.other" => "与此前 %{count} 天相比（%{start} 至 %{end}）",
  "admin_js.admin.dashboard.site_traffic.kpi.logged_in_share.label" => "已登录用户占比",
  "admin_js.admin.dashboard.site_traffic.kpi.logged_in_share.tooltip" => "已登录成员产生的页面浏览占比。",
  "admin_js.admin.dashboard.site_traffic.kpi.direct_traffic.label" => "直接访问流量",
  "admin_js.admin.dashboard.site_traffic.kpi.direct_traffic.tooltip" => "直接访问社区的页面浏览占比，例如输入网址或使用浏览器书签进入。",
  "admin_js.admin.dashboard.site_traffic.top_countries.title" => "主要国家和地区",
  "admin_js.admin.dashboard.site_traffic.top_countries.empty" => "本周期没有国家或地区数据。",
  "admin_js.admin.dashboard.site_traffic.top_countries.error" => "无法加载主要国家和地区，请刷新页面重试。",
  "admin_js.admin.dashboard.site_traffic.top_referrers.title" => "主要来源网站",
  "admin_js.admin.dashboard.site_traffic.top_referrers.empty" => "本周期没有来源网站数据。",
  "admin_js.admin.dashboard.site_traffic.top_referrers.error" => "无法加载主要来源网站，请刷新页面重试。",
  "admin_js.admin.dashboard.site_traffic.series.logged_in" => "已登录",
  "admin_js.admin.dashboard.period.custom_range" => "%{start} 至 %{end}",
  "admin_js.admin.dashboard.reports.percent_change_tooltip_previous_value.yesterday.one" => "前天为 %{count}。",
  "admin_js.admin.dashboard.reports.percent_change_tooltip_previous_value.two_weeks_ago.one" => "两周前为 %{count}。",
  "admin_js.admin.dashboard.reports.percent_change_tooltip_previous_value.thirty_days_ago.one" => "此前 30 天周期为 %{count}。",
  "admin_js.admin.groups.manage.membership.automatic_membership_email_domains_instructions" => "每行输入一个域名，例如 discourse.org。",
  "admin_js.admin.groups.manage.membership.automatic_membership_user_count.one" => "%{count} 位用户使用了新增的电子邮件域名，将被加入该群组。",
  "admin_js.admin.groups.delete_details.one" => "%{count} 人将失去对此群组的访问权限",
  "admin_js.admin.groups.delete_with_messages_confirm.one" => "%{count} 条消息将无法再被群组成员访问",
  "admin_js.admin.web_hooks.events.incoming.one" => "有一个新事件。",
  "admin_js.admin.web_hooks.events.completed_in.one" => "在 %{count} 秒内完成。",
  "admin_js.admin.web_hooks.events.redeliver_failed_confirm.one" => "确定要重新投递 %{count} 个网络钩子事件吗？",
  "admin_js.admin.config_areas.about.locale_selector.description" => "这里只显示可翻译的“关于”页面字段。",
  "admin_js.admin.config_areas.themes_and_components.components.parent_themes_more_than_three.one" => "%{name1}、%{name2}、%{name3}，以及另外 %{count} 个",
  "admin_js.admin.customize.theme.selected.one" => "已选择 %{count} 项",
  "admin_js.admin.customize.theme.and_x_more.one" => "以及另外 %{count} 项。",
  "admin_js.admin.customize.theme.up_to_date_branch" => "主题已与 %{branch} 分支保持同步，上次检查时间：",
  "admin_js.admin.customize.theme.commits_behind.one" => "主题落后 %{count} 个提交！",
  "admin_js.admin.customize.theme.commits_behind_branch.one" => "主题落后 %{branch} 分支 %{count} 个提交",
  "admin_js.admin.customize.theme.commits_behind_branch.other" => "主题落后 %{branch} 分支 %{count} 个提交",
  "admin_js.admin.customize.schema.fields.groups.at_least.one" => "至少需要 %{count} 个群组",
  "admin_js.admin.customize.schema.fields.categories.at_least.one" => "至少需要 %{count} 个类别",
  "admin_js.admin.customize.schema.fields.tags.at_least.one" => "至少需要 %{count} 个标签",
  "admin_js.admin.customize.schema.fields.string.too_short.one" => "长度至少为 %{count} 个字符",
  "admin_js.admin.logs.staff_actions.actions.recover_post" => "恢复帖子",
  "admin_js.admin.logs.staff_actions.actions.change_access_control_list_permissions" => "更改访问控制列表权限",
  "admin_js.admin.watched_words.show_words.one" => "显示 %{count} 个词",
  "admin_js.admin.users.suspend_reason" => "封禁原因",
  "admin_js.admin.users.bulk_actions.staff_cant_be_actioned" => "该用户是管理人员，无法删除或封禁",
  "admin_js.admin.users.bulk_actions.no_users_can_be_deleted" => "所选用户均无法删除。",
  "admin_js.admin.users.bulk_actions.no_users_can_be_suspended" => "所选用户均无法封禁。",
  "admin_js.admin.users.bulk_actions.too_many_selected_users.one" => "批量操作最多选择 %{count} 位用户",
  "admin_js.admin.users.bulk_actions.too_many_selected_users.other" => "批量操作最多选择 %{count} 位用户",
  "admin_js.admin.users.bulk_actions.suspend.label" => "封禁用户……",
  "admin_js.admin.users.bulk_actions.suspend.confirmation_modal.prompt_text.one" => "即将封禁 %{count} 位用户。请在下方设置期限和原因：",
  "admin_js.admin.users.bulk_actions.suspend.confirmation_modal.prompt_text.other" => "即将封禁 %{count} 位用户。请在下方设置期限和原因：",
  "admin_js.admin.users.bulk_actions.suspend.confirmation_modal.title.one" => "封禁 %{count} 位用户",
  "admin_js.admin.users.bulk_actions.suspend.confirmation_modal.title.other" => "封禁 %{count} 位用户",
  "admin_js.admin.users.bulk_actions.suspend.confirmation_modal.bulk_suspend_starting" => "正在开始批量封禁……",
  "admin_js.admin.users.bulk_actions.suspend.confirmation_modal.user_suspend_succeeded" => "[%{position}/%{total}] 已成功封禁 @%{username}",
  "admin_js.admin.users.bulk_actions.suspend.confirmation_modal.user_suspend_failed" => "[%{position}/%{total}] 无法封禁 @%{username}：%{error}",
  "admin_js.admin.users.bulk_actions.suspend.confirmation_modal.bulk_suspend_finished" => "批量封禁操作已完成。",
  "admin_js.admin.users.bulk_actions.suspend.confirmation_modal.failed_to_suspend_users" => "以下用户封禁失败：",
  "admin_js.admin.users.bulk_actions.delete.confirmation_modal.prompt_text.one" => "即将永久删除 %{count} 位用户。请在下方输入“%{confirmation_phrase}”以继续：",
  "admin_js.admin.users.bulk_actions.delete.confirmation_modal.confirmation_phrase.one" => "删除 %{count} 位用户",
  "admin_js.admin.users.bulk_actions.delete.confirmation_modal.title.one" => "删除 %{count} 位用户",
  "admin_js.admin.users.activation_filter.label" => "激活状态",
  "admin_js.admin.users.activation_filter.not_activated" => "未激活",
  "admin_js.admin.user.upcoming_changes.view_modal" => "查看已启用的更改",
  "admin_js.admin.user.exports.download.expires_in.one" => "%{count} 小时后过期",
  "admin_js.admin.user.delete_posts.progress.description.one" => "正在删除 @%{username} 的 %{count} 个帖子……",
  "admin_js.admin.user.delete_forbidden.one" => "仍有帖子的用户无法删除。请先删除所有帖子。（超过 %{count} 天的帖子无法删除。）",
  "admin_js.admin.user.cant_delete_all_posts.one" => "无法删除所有帖子，部分帖子已超过 %{count} 天。（由 delete_user_max_post_age 设置控制。）",
  "admin_js.admin.user.cant_delete_all_too_many_posts.one" => "该用户的帖子超过 %{count} 个，无法全部删除。（由 delete_all_posts_max 设置控制。）",
  "admin_js.admin.user.delete_and_block" => "删除并屏蔽电子邮件和 IP 地址",
  "admin_js.admin.user.delete_and_block_description" => "删除该用户，同时屏蔽其电子邮件地址和 IP 地址。",
  "admin_js.admin.user.delete_and_block_email" => "删除并屏蔽电子邮件",
  "admin_js.admin.user.delete_and_block_email_description" => "删除该用户并屏蔽其电子邮件地址，但允许继续使用其 IP 地址。",
  "admin_js.admin.user.delete_dont_block_description" => "删除该用户，但不屏蔽其电子邮件地址或 IP 地址。",
  "admin_js.admin.user.other_matches.one" => "另有 <b>%{count} 位用户</b>使用相同的 IP 地址。请检查并选择需要与 %{username} 一并处罚的可疑用户。",
  "admin_js.admin.user.tl3_requirements.table_title.one" => "过去一天内：",
  "admin_js.admin.site_settings.depends_on_notice.one" => "仅在启用 %{dependencyLinks} 后应用此设置。",
  "admin_js.admin.site_settings.depends_on_values_notice.one" => "仅当 %{dependencyLinks} 设为兼容值时应用此设置。",
  "admin_js.admin.site_settings.depends_on_values_notice.other" => "仅当 %{dependencyLinks} 设为兼容值时应用此设置。",
  "admin_js.admin.site_settings.discard.one" => "放弃更改",
  "admin_js.admin.site_settings.save.one" => "保存更改",
  "admin_js.admin.site_settings.dirty_banner.one" => "您有 <b>%{count}</b> 项未保存的更改",
  "admin_js.admin.site_settings.more_site_setting_results.one" => "结果超过 %{count} 个。请缩小搜索范围或选择一个类别。",
  "admin_js.admin.site_settings.default_categories.modal_description.one" => "是否将此更改应用到过去创建的账户？这将修改 %{count} 位现有用户的偏好设置。",
  "admin_js.admin.site_settings.requires_confirmation_messages.content_security_policy.prompt" => "关闭内容安全策略会移除抵御跨站脚本攻击（XSS）和其他内容注入攻击的重要保护层，使站点面临风险。此操作只能临时用于调试或测试，而且关闭内容安全策略无法解决跨域资源共享问题。确定要继续吗？",
  "admin_js.admin.site_settings.requires_confirmation_messages.content_security_policy.confirm" => "是，关闭内容安全策略",
  "admin_js.admin.badges.preview.grant_count.one" => "将授予 <b>%{count}</b> 枚徽章。",
  "admin_js.admin.badges.mass_award.success.one" => "已收到 CSV 文件，%{count} 位用户将很快获得徽章。",
  "admin_js.admin.badges.mass_award.csv_has_unmatched_users_truncated_list.one" => "CSV 文件中有 %{count} 条记录无法匹配现有用户，因此不会获得徽章。",
  "site_settings.generate_topic_og_image" => "自动为没有图片的话题生成 OpenGraph 预览图，内容取自话题标题、类别和站点颜色。",
  "site_settings.max_topics_in_first_day" => "信任级别 0 的用户在创建账户后的 24 小时内最多可以创建的话题数",
  "site_settings.max_replies_in_first_day" => "信任级别 0 的用户在创建账户后的 24 小时内最多可以发表的回复数",
  "site_settings.tl1_max_topics_in_first_day" => "信任级别 1 的用户在创建账户后的 24 小时内最多可以创建的话题数",
  "site_settings.tl1_max_replies_in_first_day" => "信任级别 1 的用户在创建账户后的 24 小时内最多可以发表的回复数",
  "site_settings.content_security_policy" => "启用内容安全策略（CSP）。CSP 是额外的安全保护层，有助于防止跨站脚本攻击（XSS）和数据注入等攻击。只能为调试或测试临时关闭。",
  "site_settings.custom_homepage_crawler_route" => "启用自定义首页时向网络爬虫显示的路由。",
  "site_settings.enable_local_logins_via_code" => "允许成员使用一次性电子邮件验证码更快地注册和登录。",
  "site_settings.google_oauth2_hd_groups" => "身份验证时获取用户在托管域中的 Google 群组。获取到的 Google 群组可用于自动授予 Discourse 群组成员资格（请参阅群组设置）。详情请参阅<a target=\"_blank\" href=\"https://meta.discourse.org/t/226850\">此 Meta 话题</a>。",
  "site_settings.enable_direct_s3_uploads" => "允许直接分段上传到 Amazon S3。详情请参阅<a target=\"_blank\" href=\"https://meta.discourse.org/t/a-new-era-for-file-uploads-in-discourse/210469\">此 Meta 话题</a>。",
  "site_settings.composer_media_optimization_image_convert_enabled" => "上传前在客户端转换 JXL、HEIC 和动态 GIF 图片。JXL 和 HEIC 会转换为 JPEG，超过阈值的动态 GIF 会转换为动态 WebP。",
  "site_settings.composer_media_optimization_gif_conversion_threshold" => "触发客户端将 GIF 转换为动态 WebP 的最小文件大小（字节）。",
  "site_settings.topic_timers_allowed_groups" => "允许设置话题计时器的群组。管理员和版主始终可以设置话题计时器。",
  "site_settings.max_quotes_per_post" => "单个帖子允许包含的最大引用数。设为 0 可关闭检查。",
  "site_settings.auto_silence_first_post_regex" => "不区分大小写的正则表达式；匹配后会将用户的首个帖子设为静默并送入审核队列。例如 raging|a[bc]a 会使首个帖子中包含 raging、aba 或 aca 的内容进入静默。仅适用于首个帖子。此设置已弃用，请改用<a href='%{base_path}/admin/customize/watched_words/action/silence'>静默关注词</a>。",
  "site_settings.email_in_authserv_id" => "对传入电子邮件执行身份验证检查的服务标识符。配置方法请参阅<a href='https://meta.discourse.org/t/134358' target='_blank'>此 Meta 话题</a>。",
  "site_settings.enable_gifs" => "在帖子编辑器中添加用于搜索和插入动图的按钮。",
  "site_settings.enable_new_chat_reactions_popup" => "启用重新设计的聊天消息回应弹窗，可无限滚动查看回应者，并提供原生移动端体验。",
  "site_settings.klipy_api_key" => "Klipy API 密钥，用于提供动图搜索功能。",
  "site_settings.klipy_file_detail" => "要使用的图片格式。WebP 文件更小、加载更快；GIF 与旧版浏览器的兼容性更好。",
  "site_settings.klipy_content_filter" => "动图搜索结果的内容安全级别。",
  "site_settings.klipy_country" => "动图搜索结果使用的两位国家或地区代码。",
  "site_settings.klipy_locale" => "动图搜索结果使用的语言代码，格式为 xx_YY（语言加可选国家或地区）。",
  "site_settings.klipy_limit_infinite_search_results" => "限制用户滚动时返回的动图结果数量，避免超过 API 速率限制。",
  "site_settings.klipy_max_results_limit" => "启用“限制无限搜索结果”后，达到此数量即停止加载。每次 API 调用会获取 24 个动图。",
  "site_settings.max_user_api_key_expiry_days" => "客户端为用户 API 密钥申请的最长有效期（天）",
  "site_settings.verbose_user_api_key_device_auth_logging" => "为用户 API 密钥的设备授权流程记录详细诊断信息",
  "site_settings.enable_horizon_high_context_topic_cards" => "在 Horizon 主题中显示信息更丰富的话题卡片，包括话题摘要、标签和插件扩展信息。",
  "site_settings.granular_anonymous_and_logged_in_groups_permissions" => "让基于群组的站点设置权限把“所有人”视为“所有已登录用户”，并启用新的“匿名用户”和“已登录用户”伪群组，使管理员能够分别指定匿名访客和已认证用户。",
  "site_settings.errors.invalid_string_min.one" => "长度至少为 %{count} 个字符。",
  "site_settings.errors.invalid_string_max.one" => "长度不能超过 %{count} 个字符。",
  "site_settings.errors.enable_local_logins_via_email_disabled" => "启用此设置前，必须先启用“允许通过电子邮件本地登录”。",
  "site_settings.errors.discourse_connect_enabled" => "启用此设置前，必须先关闭“启用 DiscourseConnect”。",
  "site_settings.errors.list_value_count.one" => "列表必须恰好包含 %{count} 个值。",
}.freeze

navigation_names = {
  "/latest" => "话题",
  "/my/activity" => "我的帖子",
  "/my/messages" => "我的消息",
  "/review" => "审核",
  "/admin" => "管理后台",
  "/new-invite" => "邀请",
  "/u" => "用户",
  "/about" => "关于",
  "/faq" => "常见问题",
  "/g" => "群组",
  "/badges" => "徽章",
  "/filter" => "筛选",
}.freeze

locale = "zh_CN"
now = Time.current
rows = translations.map do |key, value|
  original = I18n.overrides_disabled { I18n.t!(TranslationOverride.transform_pluralized_key(key), locale: :en) }
  override = TranslationOverride.find_or_initialize_by(locale: locale, translation_key: key)
  override.assign_attributes(
    value: value,
    original_translation: original,
  )
  raise "Invalid translation #{key}: #{override.errors.full_messages.join(', ')}" unless override.valid?

  {
    locale: locale,
    translation_key: key,
    value: override.sanitize_field(value, additional_attributes: %w[data-auto-route target]),
    original_translation: original,
    status: TranslationOverride.statuses.fetch("up_to_date"),
    created_at: override.created_at || now,
    updated_at: now,
  }
end
community = SidebarSection.includes(sidebar_section_links: :linkable).find_by!(public: true, section_type: :community)

unless ENV["DRY_RUN"] == "1"
  TranslationOverride.transaction do
    TranslationOverride.upsert_all(rows, unique_by: %i[locale translation_key])
  end
  TranslationOverride.reload_all_overrides!

  SidebarSection.transaction do
    community.update!(title: "社区")
    community.sidebar_section_links.each do |link|
      name = navigation_names[link.linkable&.value]
      link.linkable.update!(name: name) if name
    end
  end
  Site.clear_anon_cache!
end

action = ENV["DRY_RUN"] == "1" ? "Validated" : "Applied"
puts "#{action} #{rows.length} Simplified Chinese translation overrides and #{navigation_names.length + 1} navigation labels."
